version: '2'
services:
  db:
    image: postgres
  web:
    build: .
    command: bundle exec rails s -p 10000 -b '0.0.0.0'
    volumes:
      - .:/hypertube
    ports:
      - "10000:10000"
    depends_on:
      - db
