development: &default_db
  adapter: postgresql
  database: Hypertube_development
  encoding: utf8
  host: localhost
  min_messages: warning
  pool: 2
  timeout: 5000

test:
  <<: *default_db
  database: Hypertube_test
